// Code generated by protodump; DO NOT EDIT.
//
// Source: Factorio data-raw-dump.json
// Regenerate: go run ./protodump --factorio-dir /opt/factorio/<version>

package prototype

// AccumulatorNames contains all valid accumulator prototype names.
var AccumulatorNames = []string{
	"accumulator",
}

// AmmoTurretNames contains all valid ammo-turret prototype names.
var AmmoTurretNames = []string{
	"gun-turret",
	"railgun-turret",
	"rocket-turret",
}

// ArithmeticCombinatorNames contains all valid arithmetic-combinator prototype names.
var ArithmeticCombinatorNames = []string{
	"arithmetic-combinator",
}

// ArtilleryTurretNames contains all valid artillery-turret prototype names.
var ArtilleryTurretNames = []string{
	"artillery-turret",
}

// ArtilleryWagonNames contains all valid artillery-wagon prototype names.
var ArtilleryWagonNames = []string{
	"artillery-wagon",
}

// AssemblingMachineNames contains all valid assembling-machine prototype names.
var AssemblingMachineNames = []string{
	"assembling-machine-1",
	"assembling-machine-2",
	"assembling-machine-3",
	"biochamber",
	"captive-biter-spawner",
	"centrifuge",
	"chemical-plant",
	"crusher",
	"cryogenic-plant",
	"electromagnetic-plant",
	"foundry",
	"oil-refinery",
}

// AsteroidCollectorNames contains all valid asteroid-collector prototype names.
var AsteroidCollectorNames = []string{
	"asteroid-collector",
}

// BeaconNames contains all valid beacon prototype names.
var BeaconNames = []string{
	"beacon",
}

// BoilerNames contains all valid boiler prototype names.
var BoilerNames = []string{
	"boiler",
	"heat-exchanger",
}

// BurnerGeneratorNames contains all valid burner-generator prototype names.
var BurnerGeneratorNames = []string{
	"burner-generator",
}

// CarNames contains all valid car prototype names.
var CarNames = []string{
	"car",
	"tank",
}

// CargoBayNames contains all valid cargo-bay prototype names.
var CargoBayNames = []string{
	"cargo-bay",
}

// CargoLandingPadNames contains all valid cargo-landing-pad prototype names.
var CargoLandingPadNames = []string{
	"cargo-landing-pad",
}

// CargoWagonNames contains all valid cargo-wagon prototype names.
var CargoWagonNames = []string{
	"cargo-wagon",
}

// CharacterNames contains all valid character prototype names.
var CharacterNames = []string{
	"character",
}

// CliffNames contains all valid cliff prototype names.
var CliffNames = []string{
	"cliff",
	"cliff-fulgora",
	"cliff-gleba",
	"cliff-vulcanus",
	"crater-cliff",
}

// CombatRobotNames contains all valid combat-robot prototype names.
var CombatRobotNames = []string{
	"defender",
	"destroyer",
	"distractor",
}

// ConstantCombinatorNames contains all valid constant-combinator prototype names.
var ConstantCombinatorNames = []string{
	"constant-combinator",
}

// ConstructionRobotNames contains all valid construction-robot prototype names.
var ConstructionRobotNames = []string{
	"construction-robot",
}

// ContainerNames contains all valid container prototype names.
var ContainerNames = []string{
	"blue-chest",
	"bottomless-chest",
	"crash-site-chest-1",
	"crash-site-chest-2",
	"crash-site-spaceship",
	"crash-site-spaceship-wreck-big-1",
	"crash-site-spaceship-wreck-big-2",
	"crash-site-spaceship-wreck-medium-1",
	"crash-site-spaceship-wreck-medium-2",
	"crash-site-spaceship-wreck-medium-3",
	"factorio-logo-11tiles",
	"factorio-logo-16tiles",
	"factorio-logo-22tiles",
	"iron-chest",
	"red-chest",
	"steel-chest",
	"wooden-chest",
}

// CurvedRailANames contains all valid curved-rail-a prototype names.
var CurvedRailANames = []string{
	"curved-rail-a",
}

// CurvedRailBNames contains all valid curved-rail-b prototype names.
var CurvedRailBNames = []string{
	"curved-rail-b",
}

// DeciderCombinatorNames contains all valid decider-combinator prototype names.
var DeciderCombinatorNames = []string{
	"decider-combinator",
}

// DisplayPanelNames contains all valid display-panel prototype names.
var DisplayPanelNames = []string{
	"display-panel",
}

// ElectricEnergyInterfaceNames contains all valid electric-energy-interface prototype names.
var ElectricEnergyInterfaceNames = []string{
	"electric-energy-interface",
	"hidden-electric-energy-interface",
}

// ElectricPoleNames contains all valid electric-pole prototype names.
var ElectricPoleNames = []string{
	"big-electric-pole",
	"medium-electric-pole",
	"small-electric-pole",
	"substation",
}

// ElectricTurretNames contains all valid electric-turret prototype names.
var ElectricTurretNames = []string{
	"laser-turret",
	"tesla-turret",
}

// ElevatedCurvedRailANames contains all valid elevated-curved-rail-a prototype names.
var ElevatedCurvedRailANames = []string{
	"dummy-elevated-curved-rail-a",
	"elevated-curved-rail-a",
}

// ElevatedCurvedRailBNames contains all valid elevated-curved-rail-b prototype names.
var ElevatedCurvedRailBNames = []string{
	"dummy-elevated-curved-rail-b",
	"elevated-curved-rail-b",
}

// ElevatedHalfDiagonalRailNames contains all valid elevated-half-diagonal-rail prototype names.
var ElevatedHalfDiagonalRailNames = []string{
	"dummy-elevated-half-diagonal-rail",
	"elevated-half-diagonal-rail",
}

// ElevatedStraightRailNames contains all valid elevated-straight-rail prototype names.
var ElevatedStraightRailNames = []string{
	"dummy-elevated-straight-rail",
	"elevated-straight-rail",
}

// FluidTurretNames contains all valid fluid-turret prototype names.
var FluidTurretNames = []string{
	"flamethrower-turret",
}

// FluidWagonNames contains all valid fluid-wagon prototype names.
var FluidWagonNames = []string{
	"fluid-wagon",
}

// FurnaceNames contains all valid furnace prototype names.
var FurnaceNames = []string{
	"electric-furnace",
	"recycler",
	"steel-furnace",
	"stone-furnace",
}

// GateNames contains all valid gate prototype names.
var GateNames = []string{
	"gate",
}

// GeneratorNames contains all valid generator prototype names.
var GeneratorNames = []string{
	"steam-engine",
	"steam-turbine",
}

// HalfDiagonalRailNames contains all valid half-diagonal-rail prototype names.
var HalfDiagonalRailNames = []string{
	"half-diagonal-rail",
}

// HeatInterfaceNames contains all valid heat-interface prototype names.
var HeatInterfaceNames = []string{
	"heat-interface",
}

// HeatPipeNames contains all valid heat-pipe prototype names.
var HeatPipeNames = []string{
	"heat-pipe",
}

// InfinityContainerNames contains all valid infinity-container prototype names.
var InfinityContainerNames = []string{
	"infinity-chest",
}

// InfinityPipeNames contains all valid infinity-pipe prototype names.
var InfinityPipeNames = []string{
	"infinity-pipe",
}

// InserterNames contains all valid inserter prototype names.
var InserterNames = []string{
	"bulk-inserter",
	"burner-inserter",
	"fast-inserter",
	"inserter",
	"long-handed-inserter",
	"stack-inserter",
}

// LabNames contains all valid lab prototype names.
var LabNames = []string{
	"biolab",
	"lab",
}

// LampNames contains all valid lamp prototype names.
var LampNames = []string{
	"small-lamp",
}

// LandMineNames contains all valid land-mine prototype names.
var LandMineNames = []string{
	"land-mine",
}

// LaneSplitterNames contains all valid lane-splitter prototype names.
var LaneSplitterNames = []string{
	"lane-splitter",
}

// LinkedBeltNames contains all valid linked-belt prototype names.
var LinkedBeltNames = []string{
	"linked-belt",
}

// LinkedContainerNames contains all valid linked-container prototype names.
var LinkedContainerNames = []string{
	"linked-chest",
}

// LoaderNames contains all valid loader prototype names.
var LoaderNames = []string{
	"express-loader",
	"fast-loader",
	"loader",
	"turbo-loader",
}

// Loader1x1Names contains all valid loader-1x1 prototype names.
var Loader1x1Names = []string{
	"loader-1x1",
}

// LocomotiveNames contains all valid locomotive prototype names.
var LocomotiveNames = []string{
	"locomotive",
}

// LogisticContainerNames contains all valid logistic-container prototype names.
var LogisticContainerNames = []string{
	"active-provider-chest",
	"buffer-chest",
	"passive-provider-chest",
	"requester-chest",
	"storage-chest",
}

// LogisticRobotNames contains all valid logistic-robot prototype names.
var LogisticRobotNames = []string{
	"logistic-robot",
}

// MiningDrillNames contains all valid mining-drill prototype names.
var MiningDrillNames = []string{
	"big-mining-drill",
	"burner-mining-drill",
	"electric-mining-drill",
	"pumpjack",
}

// OffshorePumpNames contains all valid offshore-pump prototype names.
var OffshorePumpNames = []string{
	"offshore-pump",
}

// PipeNames contains all valid pipe prototype names.
var PipeNames = []string{
	"pipe",
}

// PipeToGroundNames contains all valid pipe-to-ground prototype names.
var PipeToGroundNames = []string{
	"pipe-to-ground",
}

// PowerSwitchNames contains all valid power-switch prototype names.
var PowerSwitchNames = []string{
	"power-switch",
}

// ProgrammableSpeakerNames contains all valid programmable-speaker prototype names.
var ProgrammableSpeakerNames = []string{
	"programmable-speaker",
}

// PumpNames contains all valid pump prototype names.
var PumpNames = []string{
	"pump",
}

// RadarNames contains all valid radar prototype names.
var RadarNames = []string{
	"radar",
}

// RailChainSignalNames contains all valid rail-chain-signal prototype names.
var RailChainSignalNames = []string{
	"rail-chain-signal",
}

// RailRampNames contains all valid rail-ramp prototype names.
var RailRampNames = []string{
	"dummy-rail-ramp",
	"rail-ramp",
}

// RailSignalNames contains all valid rail-signal prototype names.
var RailSignalNames = []string{
	"rail-signal",
}

// RailSupportNames contains all valid rail-support prototype names.
var RailSupportNames = []string{
	"dummy-rail-support",
	"rail-support",
}

// ReactorNames contains all valid reactor prototype names.
var ReactorNames = []string{
	"heating-tower",
	"nuclear-reactor",
}

// ResourceNames contains all valid resource prototype names.
var ResourceNames = []string{
	"calcite",
	"coal",
	"copper-ore",
	"crude-oil",
	"fluorine-vent",
	"iron-ore",
	"lithium-brine",
	"scrap",
	"stone",
	"sulfuric-acid-geyser",
	"tungsten-ore",
	"uranium-ore",
}

// RoboportNames contains all valid roboport prototype names.
var RoboportNames = []string{
	"roboport",
}

// RocketSiloNames contains all valid rocket-silo prototype names.
var RocketSiloNames = []string{
	"rocket-silo",
}

// SelectorCombinatorNames contains all valid selector-combinator prototype names.
var SelectorCombinatorNames = []string{
	"selector-combinator",
}

// SimpleEntityNames contains all valid simple-entity prototype names.
var SimpleEntityNames = []string{
	"big-demolisher-corpse",
	"big-fulgora-rock",
	"big-rock",
	"big-sand-rock",
	"big-stomper-shell",
	"big-volcanic-rock",
	"copper-stromatolite",
	"fulgoran-ruin-big",
	"fulgoran-ruin-colossal",
	"fulgoran-ruin-huge",
	"fulgoran-ruin-medium",
	"fulgoran-ruin-small",
	"fulgoran-ruin-stonehenge",
	"fulgoran-ruin-vault",
	"fulgurite",
	"fulgurite-small",
	"huge-rock",
	"huge-volcanic-rock",
	"iron-stromatolite",
	"lithium-iceberg-big",
	"lithium-iceberg-huge",
	"medium-demolisher-corpse",
	"medium-stomper-shell",
	"parameter-0",
	"parameter-1",
	"parameter-2",
	"parameter-3",
	"parameter-4",
	"parameter-5",
	"parameter-6",
	"parameter-7",
	"parameter-8",
	"parameter-9",
	"small-demolisher-corpse",
	"small-stomper-shell",
	"vulcanus-chimney",
	"vulcanus-chimney-cold",
	"vulcanus-chimney-faded",
	"vulcanus-chimney-short",
	"vulcanus-chimney-truncated",
	"wube-logo-space-platform",
}

// SimpleEntityWithForceNames contains all valid simple-entity-with-force prototype names.
var SimpleEntityWithForceNames = []string{
	"simple-entity-with-force",
}

// SimpleEntityWithOwnerNames contains all valid simple-entity-with-owner prototype names.
var SimpleEntityWithOwnerNames = []string{
	"crash-site-spaceship-wreck-small-1",
	"crash-site-spaceship-wreck-small-2",
	"crash-site-spaceship-wreck-small-3",
	"crash-site-spaceship-wreck-small-4",
	"crash-site-spaceship-wreck-small-5",
	"crash-site-spaceship-wreck-small-6",
	"simple-entity-with-owner",
}

// SolarPanelNames contains all valid solar-panel prototype names.
var SolarPanelNames = []string{
	"solar-panel",
}

// SpiderVehicleNames contains all valid spider-vehicle prototype names.
var SpiderVehicleNames = []string{
	"spidertron",
}

// SplitterNames contains all valid splitter prototype names.
var SplitterNames = []string{
	"express-splitter",
	"fast-splitter",
	"splitter",
	"turbo-splitter",
}

// StorageTankNames contains all valid storage-tank prototype names.
var StorageTankNames = []string{
	"storage-tank",
}

// StraightRailNames contains all valid straight-rail prototype names.
var StraightRailNames = []string{
	"straight-rail",
}

// TileNames contains all valid tile prototype names.
var TileNames = []string{
	"acid-refined-concrete",
	"ammoniacal-ocean",
	"ammoniacal-ocean-2",
	"artificial-jellynut-soil",
	"artificial-yumako-soil",
	"black-refined-concrete",
	"blue-refined-concrete",
	"brash-ice",
	"brown-refined-concrete",
	"concrete",
	"cyan-refined-concrete",
	"deepwater",
	"deepwater-green",
	"dirt-1",
	"dirt-2",
	"dirt-3",
	"dirt-4",
	"dirt-5",
	"dirt-6",
	"dirt-7",
	"dry-dirt",
	"dust-crests",
	"dust-flat",
	"dust-lumpy",
	"dust-patchy",
	"empty-space",
	"foundation",
	"frozen-concrete",
	"frozen-hazard-concrete-left",
	"frozen-hazard-concrete-right",
	"frozen-refined-concrete",
	"frozen-refined-hazard-concrete-left",
	"frozen-refined-hazard-concrete-right",
	"frozen-stone-path",
	"fulgoran-conduit",
	"fulgoran-dunes",
	"fulgoran-dust",
	"fulgoran-machinery",
	"fulgoran-paving",
	"fulgoran-rock",
	"fulgoran-sand",
	"fulgoran-walls",
	"gleba-deep-lake",
	"grass-1",
	"grass-2",
	"grass-3",
	"grass-4",
	"green-refined-concrete",
	"hazard-concrete-left",
	"hazard-concrete-right",
	"highland-dark-rock",
	"highland-dark-rock-2",
	"highland-yellow-rock",
	"ice-platform",
	"ice-rough",
	"ice-smooth",
	"lab-dark-1",
	"lab-dark-2",
	"lab-white",
	"landfill",
	"lava",
	"lava-hot",
	"lowland-brown-blubber",
	"lowland-cream-cauliflower",
	"lowland-cream-cauliflower-2",
	"lowland-cream-red",
	"lowland-dead-skin",
	"lowland-dead-skin-2",
	"lowland-olive-blubber",
	"lowland-olive-blubber-2",
	"lowland-olive-blubber-3",
	"lowland-pale-green",
	"lowland-red-infection",
	"lowland-red-vein",
	"lowland-red-vein-2",
	"lowland-red-vein-3",
	"lowland-red-vein-4",
	"lowland-red-vein-dead",
	"midland-cracked-lichen",
	"midland-cracked-lichen-dark",
	"midland-cracked-lichen-dull",
	"midland-turquoise-bark",
	"midland-turquoise-bark-2",
	"midland-yellow-crust",
	"midland-yellow-crust-2",
	"midland-yellow-crust-3",
	"midland-yellow-crust-4",
	"natural-jellynut-soil",
	"natural-yumako-soil",
	"nuclear-ground",
	"oil-ocean-deep",
	"oil-ocean-shallow",
	"orange-refined-concrete",
	"out-of-map",
	"overgrowth-jellynut-soil",
	"overgrowth-yumako-soil",
	"pink-refined-concrete",
	"pit-rock",
	"purple-refined-concrete",
	"red-desert-0",
	"red-desert-1",
	"red-desert-2",
	"red-desert-3",
	"red-refined-concrete",
	"refined-concrete",
	"refined-hazard-concrete-left",
	"refined-hazard-concrete-right",
	"sand-1",
	"sand-2",
	"sand-3",
	"snow-crests",
	"snow-flat",
	"snow-lumpy",
	"snow-patchy",
	"space-platform-foundation",
	"stone-path",
	"tile-unknown",
	"tutorial-grid",
	"volcanic-ash-cracks",
	"volcanic-ash-dark",
	"volcanic-ash-flats",
	"volcanic-ash-light",
	"volcanic-ash-soil",
	"volcanic-cracks",
	"volcanic-cracks-hot",
	"volcanic-cracks-warm",
	"volcanic-folds",
	"volcanic-folds-flat",
	"volcanic-folds-warm",
	"volcanic-jagged-ground",
	"volcanic-pumice-stones",
	"volcanic-smooth-stone",
	"volcanic-smooth-stone-warm",
	"volcanic-soil-dark",
	"volcanic-soil-light",
	"water",
	"water-green",
	"water-mud",
	"water-shallow",
	"water-wube",
	"wetland-blue-slime",
	"wetland-dead-skin",
	"wetland-green-slime",
	"wetland-jellynut",
	"wetland-light-dead-skin",
	"wetland-light-green-slime",
	"wetland-pink-tentacle",
	"wetland-red-tentacle",
	"wetland-yumako",
	"yellow-refined-concrete",
}

// TrainStopNames contains all valid train-stop prototype names.
var TrainStopNames = []string{
	"train-stop",
}

// TransportBeltNames contains all valid transport-belt prototype names.
var TransportBeltNames = []string{
	"express-transport-belt",
	"fast-transport-belt",
	"transport-belt",
	"turbo-transport-belt",
}

// TreeNames contains all valid tree prototype names.
var TreeNames = []string{
	"ashland-lichen-tree",
	"ashland-lichen-tree-flaming",
	"boompuff",
	"cuttlepop",
	"dead-dry-hairy-tree",
	"dead-grey-trunk",
	"dead-tree-desert",
	"dry-hairy-tree",
	"dry-tree",
	"funneltrunk",
	"hairyclubnub",
	"lickmaw",
	"slipstack",
	"stingfrond",
	"sunnycomb",
	"teflilly",
	"tree-01",
	"tree-02",
	"tree-02-red",
	"tree-03",
	"tree-04",
	"tree-05",
	"tree-06",
	"tree-06-brown",
	"tree-07",
	"tree-08",
	"tree-08-brown",
	"tree-08-red",
	"tree-09",
	"tree-09-brown",
	"tree-09-red",
	"water-cane",
}

// TurretNames contains all valid turret prototype names.
var TurretNames = []string{
	"behemoth-worm-turret",
	"big-worm-turret",
	"medium-worm-turret",
	"small-worm-turret",
}

// UndergroundBeltNames contains all valid underground-belt prototype names.
var UndergroundBeltNames = []string{
	"express-underground-belt",
	"fast-underground-belt",
	"turbo-underground-belt",
	"underground-belt",
}

// WallNames contains all valid wall prototype names.
var WallNames = []string{
	"stone-wall",
}


// ValidAccumulator is a lookup map for accumulator prototype names.
var ValidAccumulator = toSet(AccumulatorNames)

// ValidAmmoTurret is a lookup map for ammo-turret prototype names.
var ValidAmmoTurret = toSet(AmmoTurretNames)

// ValidArithmeticCombinator is a lookup map for arithmetic-combinator prototype names.
var ValidArithmeticCombinator = toSet(ArithmeticCombinatorNames)

// ValidArtilleryTurret is a lookup map for artillery-turret prototype names.
var ValidArtilleryTurret = toSet(ArtilleryTurretNames)

// ValidArtilleryWagon is a lookup map for artillery-wagon prototype names.
var ValidArtilleryWagon = toSet(ArtilleryWagonNames)

// ValidAssemblingMachine is a lookup map for assembling-machine prototype names.
var ValidAssemblingMachine = toSet(AssemblingMachineNames)

// ValidAsteroidCollector is a lookup map for asteroid-collector prototype names.
var ValidAsteroidCollector = toSet(AsteroidCollectorNames)

// ValidBeacon is a lookup map for beacon prototype names.
var ValidBeacon = toSet(BeaconNames)

// ValidBoiler is a lookup map for boiler prototype names.
var ValidBoiler = toSet(BoilerNames)

// ValidBurnerGenerator is a lookup map for burner-generator prototype names.
var ValidBurnerGenerator = toSet(BurnerGeneratorNames)

// ValidCar is a lookup map for car prototype names.
var ValidCar = toSet(CarNames)

// ValidCargoBay is a lookup map for cargo-bay prototype names.
var ValidCargoBay = toSet(CargoBayNames)

// ValidCargoLandingPad is a lookup map for cargo-landing-pad prototype names.
var ValidCargoLandingPad = toSet(CargoLandingPadNames)

// ValidCargoWagon is a lookup map for cargo-wagon prototype names.
var ValidCargoWagon = toSet(CargoWagonNames)

// ValidCharacter is a lookup map for character prototype names.
var ValidCharacter = toSet(CharacterNames)

// ValidCliff is a lookup map for cliff prototype names.
var ValidCliff = toSet(CliffNames)

// ValidCombatRobot is a lookup map for combat-robot prototype names.
var ValidCombatRobot = toSet(CombatRobotNames)

// ValidConstantCombinator is a lookup map for constant-combinator prototype names.
var ValidConstantCombinator = toSet(ConstantCombinatorNames)

// ValidConstructionRobot is a lookup map for construction-robot prototype names.
var ValidConstructionRobot = toSet(ConstructionRobotNames)

// ValidContainer is a lookup map for container prototype names.
var ValidContainer = toSet(ContainerNames)

// ValidCurvedRailA is a lookup map for curved-rail-a prototype names.
var ValidCurvedRailA = toSet(CurvedRailANames)

// ValidCurvedRailB is a lookup map for curved-rail-b prototype names.
var ValidCurvedRailB = toSet(CurvedRailBNames)

// ValidDeciderCombinator is a lookup map for decider-combinator prototype names.
var ValidDeciderCombinator = toSet(DeciderCombinatorNames)

// ValidDisplayPanel is a lookup map for display-panel prototype names.
var ValidDisplayPanel = toSet(DisplayPanelNames)

// ValidElectricEnergyInterface is a lookup map for electric-energy-interface prototype names.
var ValidElectricEnergyInterface = toSet(ElectricEnergyInterfaceNames)

// ValidElectricPole is a lookup map for electric-pole prototype names.
var ValidElectricPole = toSet(ElectricPoleNames)

// ValidElectricTurret is a lookup map for electric-turret prototype names.
var ValidElectricTurret = toSet(ElectricTurretNames)

// ValidElevatedCurvedRailA is a lookup map for elevated-curved-rail-a prototype names.
var ValidElevatedCurvedRailA = toSet(ElevatedCurvedRailANames)

// ValidElevatedCurvedRailB is a lookup map for elevated-curved-rail-b prototype names.
var ValidElevatedCurvedRailB = toSet(ElevatedCurvedRailBNames)

// ValidElevatedHalfDiagonalRail is a lookup map for elevated-half-diagonal-rail prototype names.
var ValidElevatedHalfDiagonalRail = toSet(ElevatedHalfDiagonalRailNames)

// ValidElevatedStraightRail is a lookup map for elevated-straight-rail prototype names.
var ValidElevatedStraightRail = toSet(ElevatedStraightRailNames)

// ValidFluidTurret is a lookup map for fluid-turret prototype names.
var ValidFluidTurret = toSet(FluidTurretNames)

// ValidFluidWagon is a lookup map for fluid-wagon prototype names.
var ValidFluidWagon = toSet(FluidWagonNames)

// ValidFurnace is a lookup map for furnace prototype names.
var ValidFurnace = toSet(FurnaceNames)

// ValidGate is a lookup map for gate prototype names.
var ValidGate = toSet(GateNames)

// ValidGenerator is a lookup map for generator prototype names.
var ValidGenerator = toSet(GeneratorNames)

// ValidHalfDiagonalRail is a lookup map for half-diagonal-rail prototype names.
var ValidHalfDiagonalRail = toSet(HalfDiagonalRailNames)

// ValidHeatInterface is a lookup map for heat-interface prototype names.
var ValidHeatInterface = toSet(HeatInterfaceNames)

// ValidHeatPipe is a lookup map for heat-pipe prototype names.
var ValidHeatPipe = toSet(HeatPipeNames)

// ValidInfinityContainer is a lookup map for infinity-container prototype names.
var ValidInfinityContainer = toSet(InfinityContainerNames)

// ValidInfinityPipe is a lookup map for infinity-pipe prototype names.
var ValidInfinityPipe = toSet(InfinityPipeNames)

// ValidInserter is a lookup map for inserter prototype names.
var ValidInserter = toSet(InserterNames)

// ValidLab is a lookup map for lab prototype names.
var ValidLab = toSet(LabNames)

// ValidLamp is a lookup map for lamp prototype names.
var ValidLamp = toSet(LampNames)

// ValidLandMine is a lookup map for land-mine prototype names.
var ValidLandMine = toSet(LandMineNames)

// ValidLaneSplitter is a lookup map for lane-splitter prototype names.
var ValidLaneSplitter = toSet(LaneSplitterNames)

// ValidLinkedBelt is a lookup map for linked-belt prototype names.
var ValidLinkedBelt = toSet(LinkedBeltNames)

// ValidLinkedContainer is a lookup map for linked-container prototype names.
var ValidLinkedContainer = toSet(LinkedContainerNames)

// ValidLoader is a lookup map for loader prototype names.
var ValidLoader = toSet(LoaderNames)

// ValidLoader1x1 is a lookup map for loader-1x1 prototype names.
var ValidLoader1x1 = toSet(Loader1x1Names)

// ValidLocomotive is a lookup map for locomotive prototype names.
var ValidLocomotive = toSet(LocomotiveNames)

// ValidLogisticContainer is a lookup map for logistic-container prototype names.
var ValidLogisticContainer = toSet(LogisticContainerNames)

// ValidLogisticRobot is a lookup map for logistic-robot prototype names.
var ValidLogisticRobot = toSet(LogisticRobotNames)

// ValidMiningDrill is a lookup map for mining-drill prototype names.
var ValidMiningDrill = toSet(MiningDrillNames)

// ValidOffshorePump is a lookup map for offshore-pump prototype names.
var ValidOffshorePump = toSet(OffshorePumpNames)

// ValidPipe is a lookup map for pipe prototype names.
var ValidPipe = toSet(PipeNames)

// ValidPipeToGround is a lookup map for pipe-to-ground prototype names.
var ValidPipeToGround = toSet(PipeToGroundNames)

// ValidPowerSwitch is a lookup map for power-switch prototype names.
var ValidPowerSwitch = toSet(PowerSwitchNames)

// ValidProgrammableSpeaker is a lookup map for programmable-speaker prototype names.
var ValidProgrammableSpeaker = toSet(ProgrammableSpeakerNames)

// ValidPump is a lookup map for pump prototype names.
var ValidPump = toSet(PumpNames)

// ValidRadar is a lookup map for radar prototype names.
var ValidRadar = toSet(RadarNames)

// ValidRailChainSignal is a lookup map for rail-chain-signal prototype names.
var ValidRailChainSignal = toSet(RailChainSignalNames)

// ValidRailRamp is a lookup map for rail-ramp prototype names.
var ValidRailRamp = toSet(RailRampNames)

// ValidRailSignal is a lookup map for rail-signal prototype names.
var ValidRailSignal = toSet(RailSignalNames)

// ValidRailSupport is a lookup map for rail-support prototype names.
var ValidRailSupport = toSet(RailSupportNames)

// ValidReactor is a lookup map for reactor prototype names.
var ValidReactor = toSet(ReactorNames)

// ValidResource is a lookup map for resource prototype names.
var ValidResource = toSet(ResourceNames)

// ValidRoboport is a lookup map for roboport prototype names.
var ValidRoboport = toSet(RoboportNames)

// ValidRocketSilo is a lookup map for rocket-silo prototype names.
var ValidRocketSilo = toSet(RocketSiloNames)

// ValidSelectorCombinator is a lookup map for selector-combinator prototype names.
var ValidSelectorCombinator = toSet(SelectorCombinatorNames)

// ValidSimpleEntity is a lookup map for simple-entity prototype names.
var ValidSimpleEntity = toSet(SimpleEntityNames)

// ValidSimpleEntityWithForce is a lookup map for simple-entity-with-force prototype names.
var ValidSimpleEntityWithForce = toSet(SimpleEntityWithForceNames)

// ValidSimpleEntityWithOwner is a lookup map for simple-entity-with-owner prototype names.
var ValidSimpleEntityWithOwner = toSet(SimpleEntityWithOwnerNames)

// ValidSolarPanel is a lookup map for solar-panel prototype names.
var ValidSolarPanel = toSet(SolarPanelNames)

// ValidSpiderVehicle is a lookup map for spider-vehicle prototype names.
var ValidSpiderVehicle = toSet(SpiderVehicleNames)

// ValidSplitter is a lookup map for splitter prototype names.
var ValidSplitter = toSet(SplitterNames)

// ValidStorageTank is a lookup map for storage-tank prototype names.
var ValidStorageTank = toSet(StorageTankNames)

// ValidStraightRail is a lookup map for straight-rail prototype names.
var ValidStraightRail = toSet(StraightRailNames)

// ValidTile is a lookup map for tile prototype names.
var ValidTile = toSet(TileNames)

// ValidTrainStop is a lookup map for train-stop prototype names.
var ValidTrainStop = toSet(TrainStopNames)

// ValidTransportBelt is a lookup map for transport-belt prototype names.
var ValidTransportBelt = toSet(TransportBeltNames)

// ValidTree is a lookup map for tree prototype names.
var ValidTree = toSet(TreeNames)

// ValidTurret is a lookup map for turret prototype names.
var ValidTurret = toSet(TurretNames)

// ValidUndergroundBelt is a lookup map for underground-belt prototype names.
var ValidUndergroundBelt = toSet(UndergroundBeltNames)

// ValidWall is a lookup map for wall prototype names.
var ValidWall = toSet(WallNames)

func toSet(names []string) map[string]bool {
	m := make(map[string]bool, len(names))
	for _, n := range names {
		m[n] = true
	}
	return m
}
