// Code generated by go run ./gen -- DO NOT EDIT.

package resource

import (
	"fmt"
	"strconv"
	"strings"
)

// ParseResourceDepleted parses a [resource_depleted] event message into a ResourceDepleted.
func ParseResourceDepleted(msg string) (ResourceDepleted, error) {
	payload := msg
	prefix := "[resource_depleted] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 6 {
		return ResourceDepleted{}, fmt.Errorf("expected 6 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 6 {
		return ResourceDepleted{}, fmt.Errorf("expected 6 :-separated fields, got %d", len(parts))
	}

	var result ResourceDepleted
	var err error
	_ = err

	result.Name = parts[0]

	result.X, err = strconv.ParseFloat(parts[1], 64)
	if err != nil {
		return result, fmt.Errorf("invalid X %q: %w", parts[1], err)
	}

	result.Y, err = strconv.ParseFloat(parts[2], 64)
	if err != nil {
		return result, fmt.Errorf("invalid Y %q: %w", parts[2], err)
	}

	result.Amount, err = strconv.ParseUint(parts[3], 10, 64)
	if err != nil {
		return result, fmt.Errorf("invalid Amount %q: %w", parts[3], err)
	}

	result.SurfaceName = parts[4]

	result.SurfaceIndex, err = strconv.Atoi(parts[5])
	if err != nil {
		return result, fmt.Errorf("invalid SurfaceIndex %q: %w", parts[5], err)
	}

	return result, nil
}

// Format returns the wire-format string for this ResourceDepleted.
func (m ResourceDepleted) Format() string {
	tag := "resource_depleted"
	return "[" + tag + "] " + m.Name + ":" + strconv.FormatFloat(m.X, 'f', 1, 64) + ":" + strconv.FormatFloat(m.Y, 'f', 1, 64) + ":" + strconv.FormatUint(m.Amount, 10) + ":" + m.SurfaceName + ":" + strconv.Itoa(m.SurfaceIndex)
}
