-- Code generated by go run ./gen -- DO NOT EDIT.

local entity_mod = {}

local function emit_entity(tag, event, include_cause)
    local entity = event.entity
    if not (entity and entity.valid) then return end

    local surface = entity.surface
    if not (surface and surface.valid) then return end

    local player_index = event.player_index or 0
    local unit_number = entity.unit_number or 0

    local cause = ""
    if include_cause and event.cause and event.cause.valid then
        cause = event.cause.name
    end

    local msg = string.format("[%s] %s:%.1f:%.1f:%d:%s:%d:%d:%s",
        tag,
        entity.name,
        entity.position.x,
        entity.position.y,
        unit_number,
        surface.name,
        surface.index,
        player_index,
        cause)

    helpers.send_udp(4000, msg, 0)
end

local function on_entity_died(event)
    emit_entity("entity_died", event, true)
end

local function on_built_entity(event)
    emit_entity("entity_built", event, false)
end

local function on_robot_built_entity(event)
    emit_entity("entity_built", event, false)
end

local function on_player_mined_entity(event)
    emit_entity("entity_mined", event, false)
end

local function on_robot_mined_entity(event)
    emit_entity("entity_mined", event, false)
end

entity_mod.events = {
    [defines.events.on_entity_died] = on_entity_died,
    [defines.events.on_built_entity] = on_built_entity,
    [defines.events.on_robot_built_entity] = on_robot_built_entity,
    [defines.events.on_player_mined_entity] = on_player_mined_entity,
    [defines.events.on_robot_mined_entity] = on_robot_mined_entity,
}

return entity_mod
