-- Code generated by go run ./gen -- DO NOT EDIT.

local game_mod = {}

local TICK_INTERVAL = 60

local function on_tick(event)
    local msg = string.format("[game_tick] %d", game.tick)
    helpers.send_udp(4000, msg, 0)
end

game_mod.on_nth_tick = {
    [TICK_INTERVAL] = on_tick,
}

return game_mod
