-- Code generated by go run ./gen -- DO NOT EDIT.

local playerattr_mod = {}

local function on_player_joined_game(event)
    local player = game.players[event.player_index]
    if not (player and player.valid) then return end

    local msg = string.format("[player_joined] %s:%d", player.name, player.index)
    helpers.send_udp(4000, msg, 0)
end

local function on_player_left_game(event)
    local player = game.players[event.player_index]
    if not (player and player.valid) then return end

    local msg = string.format("[player_left] %s:%d", player.name, player.index)
    helpers.send_udp(4000, msg, 0)
end

local function on_player_died(event)
    local player = game.players[event.player_index]
    if not (player and player.valid) then return end

    local msg = string.format("[player_died] %s:%d", player.name, player.index)
    helpers.send_udp(4000, msg, 0)
end

local function on_player_respawned(event)
    local player = game.players[event.player_index]
    if not (player and player.valid) then return end

    local msg = string.format("[player_respawned] %s:%d", player.name, player.index)
    helpers.send_udp(4000, msg, 0)
end

playerattr_mod.events = {
    [defines.events.on_player_joined_game] = on_player_joined_game,
    [defines.events.on_player_left_game] = on_player_left_game,
    [defines.events.on_player_died] = on_player_died,
    [defines.events.on_player_respawned] = on_player_respawned,
}

return playerattr_mod
