-- Code generated by go run ./gen -- DO NOT EDIT.

local resource_mod = {}

local function on_resource_depleted(event)
    local entity = event.entity
    if not (entity and entity.valid) then return end

    local surface = entity.surface
    if not (surface and surface.valid) then return end

    local msg = string.format("[resource_depleted] %s:%.1f:%.1f:%d:%s:%d",
        entity.name,
        entity.position.x,
        entity.position.y,
        entity.amount,
        surface.name,
        surface.index)
    helpers.send_udp(4000, msg, 0)
end

resource_mod.events = {
    [defines.events.on_resource_depleted] = on_resource_depleted,
}

return resource_mod
