-- Code generated by go run ./gen -- DO NOT EDIT.

local surface_mod = {}

local function on_surface_created(event)
    local surface = game.surfaces[event.surface_index]
    if not (surface and surface.valid) then return end

    local msg = string.format("[surface_created] %s:%d", surface.name, surface.index)
    helpers.send_udp(4000, msg, 0)
end

local function on_surface_deleted(event)
    local surface = game.surfaces[event.surface_index]
    if surface and surface.valid then
        local msg = string.format("[surface_deleted] %s:%d", surface.name, surface.index)
        helpers.send_udp(4000, msg, 0)
    else
        local msg = string.format("[surface_deleted] %s:%d", "", event.surface_index)
        helpers.send_udp(4000, msg, 0)
    end
end

surface_mod.events = {
    [defines.events.on_surface_created] = on_surface_created,
    [defines.events.on_surface_deleted] = on_surface_deleted,
}

return surface_mod
