-- Code generated by go run ./gen -- DO NOT EDIT.

local tile_mod = {}

local function handle_tile_event(event, tag)
    local surface = game.surfaces[event.surface_index]
    if not (surface and surface.valid) then return end

    local player_index = event.player_index or 0
    local surface_index = surface.index
    local surface_name = surface.name

    for _, tile in pairs(event.tiles) do
        local name = tile.old_tile.name
        local x = tile.position.x
        local y = tile.position.y
        local msg = string.format("[%s] %s:%.1f:%.1f:%s:%d:%d",
            tag,
            name,
            x,
            y,
            surface_name,
            surface_index,
            player_index)
        helpers.send_udp(4000, msg, 0)
    end
end

local function on_player_built_tile(event)
    handle_tile_event(event, "tile_built")
end

local function on_robot_built_tile(event)
    handle_tile_event(event, "tile_built")
end

local function on_player_mined_tile(event)
    handle_tile_event(event, "tile_mined")
end

local function on_robot_mined_tile(event)
    handle_tile_event(event, "tile_mined")
end

tile_mod.events = {
    [defines.events.on_player_built_tile] = on_player_built_tile,
    [defines.events.on_robot_built_tile] = on_robot_built_tile,
    [defines.events.on_player_mined_tile] = on_player_mined_tile,
    [defines.events.on_robot_mined_tile] = on_robot_mined_tile,
}

return tile_mod
