// Code generated by go run ./gen -- DO NOT EDIT.

package tile

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseTileEventTileBuilt_RoundTrip(t *testing.T) {
	input := TileEvent{
		Event:        "tile_built",
		Name:         "testName",
		X:            12.5,
		Y:            12.5,
		SurfaceName:  "testSurfaceName",
		SurfaceIndex: 42,
		PlayerIndex:  42,
	}
	formatted := input.Format()
	parsed, err := ParseTileEventTileBuilt(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.InDelta(t, input.X, parsed.X, 0.001)
	assert.InDelta(t, input.Y, parsed.Y, 0.001)
	assert.Equal(t, input.SurfaceName, parsed.SurfaceName)
	assert.Equal(t, input.SurfaceIndex, parsed.SurfaceIndex)
	assert.Equal(t, input.PlayerIndex, parsed.PlayerIndex)
}

func TestParseTileEventTileBuilt_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid X", input: "valid:notanumber:1.0:valid:1:1"},
		{name: "invalid Y", input: "valid:1.0:notanumber:valid:1:1"},
		{name: "invalid SurfaceIndex", input: "valid:1.0:1.0:valid:notanumber:1"},
		{name: "invalid PlayerIndex", input: "valid:1.0:1.0:valid:1:notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseTileEventTileBuilt(tc.input)
			assert.Error(t, err)
		})
	}
}

func TestParseTileEventTileMined_RoundTrip(t *testing.T) {
	input := TileEvent{
		Event:        "tile_mined",
		Name:         "testName",
		X:            12.5,
		Y:            12.5,
		SurfaceName:  "testSurfaceName",
		SurfaceIndex: 42,
		PlayerIndex:  42,
	}
	formatted := input.Format()
	parsed, err := ParseTileEventTileMined(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.InDelta(t, input.X, parsed.X, 0.001)
	assert.InDelta(t, input.Y, parsed.Y, 0.001)
	assert.Equal(t, input.SurfaceName, parsed.SurfaceName)
	assert.Equal(t, input.SurfaceIndex, parsed.SurfaceIndex)
	assert.Equal(t, input.PlayerIndex, parsed.PlayerIndex)
}

func TestParseTileEventTileMined_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid X", input: "valid:notanumber:1.0:valid:1:1"},
		{name: "invalid Y", input: "valid:1.0:notanumber:valid:1:1"},
		{name: "invalid SurfaceIndex", input: "valid:1.0:1.0:valid:notanumber:1"},
		{name: "invalid PlayerIndex", input: "valid:1.0:1.0:valid:1:notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseTileEventTileMined(tc.input)
			assert.Error(t, err)
		})
	}
}
