// Code generated by go run ./gen -- DO NOT EDIT.

package tile

import (
	"fmt"
	"strconv"
	"strings"
)

// ParseTileEventTileBuilt parses a [tile_built] event message into a TileEvent.
func ParseTileEventTileBuilt(msg string) (TileEvent, error) {
	payload := msg
	prefix := "[tile_built] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 6 {
		return TileEvent{}, fmt.Errorf("expected 6 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 6 {
		return TileEvent{}, fmt.Errorf("expected 6 :-separated fields, got %d", len(parts))
	}

	var result TileEvent
	var err error
	_ = err

	result.Event = "tile_built"

	result.Name = parts[0]

	result.X, err = strconv.ParseFloat(parts[1], 64)
	if err != nil {
		return result, fmt.Errorf("invalid X %q: %w", parts[1], err)
	}

	result.Y, err = strconv.ParseFloat(parts[2], 64)
	if err != nil {
		return result, fmt.Errorf("invalid Y %q: %w", parts[2], err)
	}

	result.SurfaceName = parts[3]

	result.SurfaceIndex, err = strconv.Atoi(parts[4])
	if err != nil {
		return result, fmt.Errorf("invalid SurfaceIndex %q: %w", parts[4], err)
	}

	result.PlayerIndex, err = strconv.Atoi(parts[5])
	if err != nil {
		return result, fmt.Errorf("invalid PlayerIndex %q: %w", parts[5], err)
	}

	return result, nil
}

// ParseTileEventTileMined parses a [tile_mined] event message into a TileEvent.
func ParseTileEventTileMined(msg string) (TileEvent, error) {
	payload := msg
	prefix := "[tile_mined] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 6 {
		return TileEvent{}, fmt.Errorf("expected 6 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 6 {
		return TileEvent{}, fmt.Errorf("expected 6 :-separated fields, got %d", len(parts))
	}

	var result TileEvent
	var err error
	_ = err

	result.Event = "tile_mined"

	result.Name = parts[0]

	result.X, err = strconv.ParseFloat(parts[1], 64)
	if err != nil {
		return result, fmt.Errorf("invalid X %q: %w", parts[1], err)
	}

	result.Y, err = strconv.ParseFloat(parts[2], 64)
	if err != nil {
		return result, fmt.Errorf("invalid Y %q: %w", parts[2], err)
	}

	result.SurfaceName = parts[3]

	result.SurfaceIndex, err = strconv.Atoi(parts[4])
	if err != nil {
		return result, fmt.Errorf("invalid SurfaceIndex %q: %w", parts[4], err)
	}

	result.PlayerIndex, err = strconv.Atoi(parts[5])
	if err != nil {
		return result, fmt.Errorf("invalid PlayerIndex %q: %w", parts[5], err)
	}

	return result, nil
}

// Format returns the wire-format string for this TileEvent.
func (m TileEvent) Format() string {
	tag := m.Event
	return "[" + tag + "] " + m.Name + ":" + strconv.FormatFloat(m.X, 'f', 1, 64) + ":" + strconv.FormatFloat(m.Y, 'f', 1, 64) + ":" + m.SurfaceName + ":" + strconv.Itoa(m.SurfaceIndex) + ":" + strconv.Itoa(m.PlayerIndex)
}
