package main

import (
	"os"
	"text/template"
)

var goTemplate = template.Must(template.New("prototypes").Parse(`// Code generated by protodump; DO NOT EDIT.
//
// Source: Factorio data-raw-dump.json
// Regenerate: go run ./protodump --factorio-dir /opt/factorio/<version>

package prototype
{{range .Groups}}
// {{.GoID}}Names contains all valid {{.Type}} prototype names.
var {{.GoID}}Names = []string{
{{- range .Names}}
	"{{.}}",
{{- end}}
}
{{end}}
{{range .Groups}}
// Valid{{.GoID}} is a lookup map for {{.Type}} prototype names.
var Valid{{.GoID}} = toSet({{.GoID}}Names)
{{end}}
func toSet(names []string) map[string]bool {
	m := make(map[string]bool, len(names))
	for _, n := range names {
		m[n] = true
	}
	return m
}
`))

type templateData struct {
	Groups []ProtoGroup
}

func writeGoFile(path string, groups []ProtoGroup) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return goTemplate.Execute(f, templateData{Groups: groups})
}
