// Code generated by go run ./gen -- DO NOT EDIT.

package player

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseMove_RoundTrip(t *testing.T) {
	input := Move{
		Name:         "testName",
		Index:        42,
		X:            12.5,
		Y:            12.5,
		SurfaceName:  "testSurfaceName",
		SurfaceIndex: 42,
	}
	formatted := input.Format()
	parsed, err := ParseMove(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.Equal(t, input.Index, parsed.Index)
	assert.InDelta(t, input.X, parsed.X, 0.001)
	assert.InDelta(t, input.Y, parsed.Y, 0.001)
	assert.Equal(t, input.SurfaceName, parsed.SurfaceName)
	assert.Equal(t, input.SurfaceIndex, parsed.SurfaceIndex)
}

func TestParseMove_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid Index", input: "valid:notanumber:1.0:1.0:valid:1"},
		{name: "invalid X", input: "valid:1:notanumber:1.0:valid:1"},
		{name: "invalid Y", input: "valid:1:1.0:notanumber:valid:1"},
		{name: "invalid SurfaceIndex", input: "valid:1:1.0:1.0:valid:notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseMove(tc.input)
			assert.Error(t, err)
		})
	}
}
