// Code generated by go run ./gen -- DO NOT EDIT.

package player

import (
	"fmt"
	"strconv"
	"strings"
)

// ParseMove parses a [move] event message into a Move.
func ParseMove(msg string) (Move, error) {
	payload := msg
	prefix := "[move] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 6 {
		return Move{}, fmt.Errorf("expected 6 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 6 {
		return Move{}, fmt.Errorf("expected 6 :-separated fields, got %d", len(parts))
	}

	var result Move
	var err error
	_ = err

	result.Name = parts[0]

	result.Index, err = strconv.Atoi(parts[1])
	if err != nil {
		return result, fmt.Errorf("invalid Index %q: %w", parts[1], err)
	}

	result.X, err = strconv.ParseFloat(parts[2], 64)
	if err != nil {
		return result, fmt.Errorf("invalid X %q: %w", parts[2], err)
	}

	result.Y, err = strconv.ParseFloat(parts[3], 64)
	if err != nil {
		return result, fmt.Errorf("invalid Y %q: %w", parts[3], err)
	}

	result.SurfaceName = parts[4]

	result.SurfaceIndex, err = strconv.Atoi(parts[5])
	if err != nil {
		return result, fmt.Errorf("invalid SurfaceIndex %q: %w", parts[5], err)
	}

	return result, nil
}

// Format returns the wire-format string for this Move.
func (m Move) Format() string {
	tag := "move"
	return "[" + tag + "] " + m.Name + ":" + strconv.Itoa(m.Index) + ":" + strconv.FormatFloat(m.X, 'f', 1, 64) + ":" + strconv.FormatFloat(m.Y, 'f', 1, 64) + ":" + m.SurfaceName + ":" + strconv.Itoa(m.SurfaceIndex)
}
