// Code generated by go run ./gen -- DO NOT EDIT.

package game

import (
	"fmt"
	"strconv"
	"strings"
)

// ParseTickEvent parses a [game_tick] event message into a TickEvent.
func ParseTickEvent(msg string) (TickEvent, error) {
	payload := msg
	prefix := "[game_tick] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 1 {
		return TickEvent{}, fmt.Errorf("expected 1 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 1 {
		return TickEvent{}, fmt.Errorf("expected 1 :-separated fields, got %d", len(parts))
	}

	var result TickEvent
	var err error
	_ = err

	result.Tick, err = strconv.ParseUint(parts[0], 10, 64)
	if err != nil {
		return result, fmt.Errorf("invalid Tick %q: %w", parts[0], err)
	}

	return result, nil
}

// Format returns the wire-format string for this TickEvent.
func (m TickEvent) Format() string {
	tag := "game_tick"
	return "[" + tag + "] " + strconv.FormatUint(m.Tick, 10)
}
