// Code generated by go run ./gen -- DO NOT EDIT.

package game

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseTickEvent_RoundTrip(t *testing.T) {
	input := TickEvent{
		Tick: 100,
	}
	formatted := input.Format()
	parsed, err := ParseTickEvent(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Tick, parsed.Tick)
}

func TestParseTickEvent_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: ""},
		{name: "invalid Tick", input: "notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseTickEvent(tc.input)
			assert.Error(t, err)
		})
	}
}
