// Code generated by go run ./gen -- DO NOT EDIT.

package plugin

import "github.com/mlctrez/factop/client/playerattr"

// OnPlayerJoined registers a handler for [player_joined] events.
func (r *EventRouter) OnPlayerJoined(fn func(playerattr.PlayerEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("player_joined"); err != nil {
		return err
	}

	ts := r.tags["player_joined"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(playerattr.PlayerEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return playerattr.ParsePlayerEventPlayerJoined(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(playerattr.PlayerEvent)) }},
		})
	}
	return nil
}

// OnPlayerLeft registers a handler for [player_left] events.
func (r *EventRouter) OnPlayerLeft(fn func(playerattr.PlayerEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("player_left"); err != nil {
		return err
	}

	ts := r.tags["player_left"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(playerattr.PlayerEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return playerattr.ParsePlayerEventPlayerLeft(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(playerattr.PlayerEvent)) }},
		})
	}
	return nil
}

// OnPlayerDied registers a handler for [player_died] events.
func (r *EventRouter) OnPlayerDied(fn func(playerattr.PlayerEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("player_died"); err != nil {
		return err
	}

	ts := r.tags["player_died"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(playerattr.PlayerEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return playerattr.ParsePlayerEventPlayerDied(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(playerattr.PlayerEvent)) }},
		})
	}
	return nil
}

// OnPlayerRespawned registers a handler for [player_respawned] events.
func (r *EventRouter) OnPlayerRespawned(fn func(playerattr.PlayerEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("player_respawned"); err != nil {
		return err
	}

	ts := r.tags["player_respawned"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(playerattr.PlayerEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return playerattr.ParsePlayerEventPlayerRespawned(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(playerattr.PlayerEvent)) }},
		})
	}
	return nil
}
