// Code generated by go run ./gen -- DO NOT EDIT.

package plugin

import "github.com/mlctrez/factop/client/entity"

// OnEntityDied registers a handler for [entity_died] events.
func (r *EventRouter) OnEntityDied(fn func(entity.EntityEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("entity_died"); err != nil {
		return err
	}

	ts := r.tags["entity_died"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(entity.EntityEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return entity.ParseEntityEventEntityDied(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(entity.EntityEvent)) }},
		})
	}
	return nil
}

// OnEntityBuilt registers a handler for [entity_built] events.
func (r *EventRouter) OnEntityBuilt(fn func(entity.EntityEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("entity_built"); err != nil {
		return err
	}

	ts := r.tags["entity_built"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(entity.EntityEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return entity.ParseEntityEventEntityBuilt(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(entity.EntityEvent)) }},
		})
	}
	return nil
}

// OnEntityMined registers a handler for [entity_mined] events.
func (r *EventRouter) OnEntityMined(fn func(entity.EntityEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("entity_mined"); err != nil {
		return err
	}

	ts := r.tags["entity_mined"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(entity.EntityEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return entity.ParseEntityEventEntityMined(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(entity.EntityEvent)) }},
		})
	}
	return nil
}
