// Code generated by go run ./gen -- DO NOT EDIT.

package plugin

import "github.com/mlctrez/factop/client/tile"

// OnTileBuilt registers a handler for [tile_built] events.
func (r *EventRouter) OnTileBuilt(fn func(tile.TileEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("tile_built"); err != nil {
		return err
	}

	ts := r.tags["tile_built"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(tile.TileEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return tile.ParseTileEventTileBuilt(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(tile.TileEvent)) }},
		})
	}
	return nil
}

// OnTileMined registers a handler for [tile_mined] events.
func (r *EventRouter) OnTileMined(fn func(tile.TileEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("tile_mined"); err != nil {
		return err
	}

	ts := r.tags["tile_mined"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(tile.TileEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return tile.ParseTileEventTileMined(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(tile.TileEvent)) }},
		})
	}
	return nil
}
