// Code generated by go run ./gen -- DO NOT EDIT.

package plugin

import "github.com/mlctrez/factop/client/player"

// OnMove registers a handler for [move] events.
func (r *EventRouter) OnMove(fn func(player.Move)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("move"); err != nil {
		return err
	}

	ts := r.tags["move"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(player.Move))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return player.ParseMove(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(player.Move)) }},
		})
	}
	return nil
}
