// Code generated by go run ./gen -- DO NOT EDIT.

package plugin

import "github.com/mlctrez/factop/client/surface"

// OnSurfaceCreated registers a handler for [surface_created] events.
func (r *EventRouter) OnSurfaceCreated(fn func(surface.SurfaceEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("surface_created"); err != nil {
		return err
	}

	ts := r.tags["surface_created"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(surface.SurfaceEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return surface.ParseSurfaceEventSurfaceCreated(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(surface.SurfaceEvent)) }},
		})
	}
	return nil
}

// OnSurfaceDeleted registers a handler for [surface_deleted] events.
func (r *EventRouter) OnSurfaceDeleted(fn func(surface.SurfaceEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("surface_deleted"); err != nil {
		return err
	}

	ts := r.tags["surface_deleted"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(surface.SurfaceEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return surface.ParseSurfaceEventSurfaceDeleted(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(surface.SurfaceEvent)) }},
		})
	}
	return nil
}
