// Code generated by go run ./gen -- DO NOT EDIT.

package plugin

import "github.com/mlctrez/factop/client/game"

// OnGameTick registers a handler for [game_tick] events.
func (r *EventRouter) OnGameTick(fn func(game.TickEvent)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("game_tick"); err != nil {
		return err
	}

	ts := r.tags["game_tick"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(game.TickEvent))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return game.ParseTickEvent(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(game.TickEvent)) }},
		})
	}
	return nil
}
