// Code generated by go run ./gen -- DO NOT EDIT.

package plugin

import "github.com/mlctrez/factop/client/resource"

// OnResourceDepleted registers a handler for [resource_depleted] events.
func (r *EventRouter) OnResourceDepleted(fn func(resource.ResourceDepleted)) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if err := r.subscribe("resource_depleted"); err != nil {
		return err
	}

	ts := r.tags["resource_depleted"]
	found := false
	for i := range ts.typed {
		if ts.typed[i].parse != nil {
			ts.typed[i].handlers = append(ts.typed[i].handlers, func(v any) {
				fn(v.(resource.ResourceDepleted))
			})
			found = true
			break
		}
	}
	if !found {
		ts.typed = append(ts.typed, typedHandler{
			parse: func(data []byte) (any, error) {
				return resource.ParseResourceDepleted(string(data))
			},
			handlers: []func(any){func(v any) { fn(v.(resource.ResourceDepleted)) }},
		})
	}
	return nil
}
