// Code generated by go run ./gen -- DO NOT EDIT.

package entity

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseEntityEventEntityDied_RoundTrip(t *testing.T) {
	input := EntityEvent{
		Event:        "entity_died",
		Name:         "testName",
		X:            12.5,
		Y:            12.5,
		UnitNumber:   100,
		SurfaceName:  "testSurfaceName",
		SurfaceIndex: 42,
		PlayerIndex:  42,
		Cause:        "testCause",
	}
	formatted := input.Format()
	parsed, err := ParseEntityEventEntityDied(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.InDelta(t, input.X, parsed.X, 0.001)
	assert.InDelta(t, input.Y, parsed.Y, 0.001)
	assert.Equal(t, input.UnitNumber, parsed.UnitNumber)
	assert.Equal(t, input.SurfaceName, parsed.SurfaceName)
	assert.Equal(t, input.SurfaceIndex, parsed.SurfaceIndex)
	assert.Equal(t, input.PlayerIndex, parsed.PlayerIndex)
	assert.Equal(t, input.Cause, parsed.Cause)
}

func TestParseEntityEventEntityDied_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid X", input: "valid:notanumber:1.0:1:valid:1:1:valid"},
		{name: "invalid Y", input: "valid:1.0:notanumber:1:valid:1:1:valid"},
		{name: "invalid UnitNumber", input: "valid:1.0:1.0:notanumber:valid:1:1:valid"},
		{name: "invalid SurfaceIndex", input: "valid:1.0:1.0:1:valid:notanumber:1:valid"},
		{name: "invalid PlayerIndex", input: "valid:1.0:1.0:1:valid:1:notanumber:valid"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseEntityEventEntityDied(tc.input)
			assert.Error(t, err)
		})
	}
}

func TestParseEntityEventEntityBuilt_RoundTrip(t *testing.T) {
	input := EntityEvent{
		Event:        "entity_built",
		Name:         "testName",
		X:            12.5,
		Y:            12.5,
		UnitNumber:   100,
		SurfaceName:  "testSurfaceName",
		SurfaceIndex: 42,
		PlayerIndex:  42,
		Cause:        "testCause",
	}
	formatted := input.Format()
	parsed, err := ParseEntityEventEntityBuilt(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.InDelta(t, input.X, parsed.X, 0.001)
	assert.InDelta(t, input.Y, parsed.Y, 0.001)
	assert.Equal(t, input.UnitNumber, parsed.UnitNumber)
	assert.Equal(t, input.SurfaceName, parsed.SurfaceName)
	assert.Equal(t, input.SurfaceIndex, parsed.SurfaceIndex)
	assert.Equal(t, input.PlayerIndex, parsed.PlayerIndex)
	assert.Equal(t, input.Cause, parsed.Cause)
}

func TestParseEntityEventEntityBuilt_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid X", input: "valid:notanumber:1.0:1:valid:1:1:valid"},
		{name: "invalid Y", input: "valid:1.0:notanumber:1:valid:1:1:valid"},
		{name: "invalid UnitNumber", input: "valid:1.0:1.0:notanumber:valid:1:1:valid"},
		{name: "invalid SurfaceIndex", input: "valid:1.0:1.0:1:valid:notanumber:1:valid"},
		{name: "invalid PlayerIndex", input: "valid:1.0:1.0:1:valid:1:notanumber:valid"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseEntityEventEntityBuilt(tc.input)
			assert.Error(t, err)
		})
	}
}

func TestParseEntityEventEntityMined_RoundTrip(t *testing.T) {
	input := EntityEvent{
		Event:        "entity_mined",
		Name:         "testName",
		X:            12.5,
		Y:            12.5,
		UnitNumber:   100,
		SurfaceName:  "testSurfaceName",
		SurfaceIndex: 42,
		PlayerIndex:  42,
		Cause:        "testCause",
	}
	formatted := input.Format()
	parsed, err := ParseEntityEventEntityMined(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.InDelta(t, input.X, parsed.X, 0.001)
	assert.InDelta(t, input.Y, parsed.Y, 0.001)
	assert.Equal(t, input.UnitNumber, parsed.UnitNumber)
	assert.Equal(t, input.SurfaceName, parsed.SurfaceName)
	assert.Equal(t, input.SurfaceIndex, parsed.SurfaceIndex)
	assert.Equal(t, input.PlayerIndex, parsed.PlayerIndex)
	assert.Equal(t, input.Cause, parsed.Cause)
}

func TestParseEntityEventEntityMined_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid X", input: "valid:notanumber:1.0:1:valid:1:1:valid"},
		{name: "invalid Y", input: "valid:1.0:notanumber:1:valid:1:1:valid"},
		{name: "invalid UnitNumber", input: "valid:1.0:1.0:notanumber:valid:1:1:valid"},
		{name: "invalid SurfaceIndex", input: "valid:1.0:1.0:1:valid:notanumber:1:valid"},
		{name: "invalid PlayerIndex", input: "valid:1.0:1.0:1:valid:1:notanumber:valid"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseEntityEventEntityMined(tc.input)
			assert.Error(t, err)
		})
	}
}
