// Code generated by go run ./gen -- DO NOT EDIT.

package entity

import (
	"fmt"
	"strconv"
	"strings"
)

// ParseEntityEventEntityDied parses a [entity_died] event message into a EntityEvent.
func ParseEntityEventEntityDied(msg string) (EntityEvent, error) {
	payload := msg
	prefix := "[entity_died] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 7 {
		return EntityEvent{}, fmt.Errorf("expected 7 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 8 {
		return EntityEvent{}, fmt.Errorf("expected 8 :-separated fields, got %d", len(parts))
	}

	var result EntityEvent
	var err error
	_ = err

	result.Event = "entity_died"

	result.Name = parts[0]

	result.X, err = strconv.ParseFloat(parts[1], 64)
	if err != nil {
		return result, fmt.Errorf("invalid X %q: %w", parts[1], err)
	}

	result.Y, err = strconv.ParseFloat(parts[2], 64)
	if err != nil {
		return result, fmt.Errorf("invalid Y %q: %w", parts[2], err)
	}

	result.UnitNumber, err = strconv.ParseUint(parts[3], 10, 64)
	if err != nil {
		return result, fmt.Errorf("invalid UnitNumber %q: %w", parts[3], err)
	}

	result.SurfaceName = parts[4]

	result.SurfaceIndex, err = strconv.Atoi(parts[5])
	if err != nil {
		return result, fmt.Errorf("invalid SurfaceIndex %q: %w", parts[5], err)
	}

	result.PlayerIndex, err = strconv.Atoi(parts[6])
	if err != nil {
		return result, fmt.Errorf("invalid PlayerIndex %q: %w", parts[6], err)
	}

	if len(parts) > 7 {
		result.Cause = parts[7]
	}

	return result, nil
}

// ParseEntityEventEntityBuilt parses a [entity_built] event message into a EntityEvent.
func ParseEntityEventEntityBuilt(msg string) (EntityEvent, error) {
	payload := msg
	prefix := "[entity_built] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 7 {
		return EntityEvent{}, fmt.Errorf("expected 7 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 8 {
		return EntityEvent{}, fmt.Errorf("expected 8 :-separated fields, got %d", len(parts))
	}

	var result EntityEvent
	var err error
	_ = err

	result.Event = "entity_built"

	result.Name = parts[0]

	result.X, err = strconv.ParseFloat(parts[1], 64)
	if err != nil {
		return result, fmt.Errorf("invalid X %q: %w", parts[1], err)
	}

	result.Y, err = strconv.ParseFloat(parts[2], 64)
	if err != nil {
		return result, fmt.Errorf("invalid Y %q: %w", parts[2], err)
	}

	result.UnitNumber, err = strconv.ParseUint(parts[3], 10, 64)
	if err != nil {
		return result, fmt.Errorf("invalid UnitNumber %q: %w", parts[3], err)
	}

	result.SurfaceName = parts[4]

	result.SurfaceIndex, err = strconv.Atoi(parts[5])
	if err != nil {
		return result, fmt.Errorf("invalid SurfaceIndex %q: %w", parts[5], err)
	}

	result.PlayerIndex, err = strconv.Atoi(parts[6])
	if err != nil {
		return result, fmt.Errorf("invalid PlayerIndex %q: %w", parts[6], err)
	}

	if len(parts) > 7 {
		result.Cause = parts[7]
	}

	return result, nil
}

// ParseEntityEventEntityMined parses a [entity_mined] event message into a EntityEvent.
func ParseEntityEventEntityMined(msg string) (EntityEvent, error) {
	payload := msg
	prefix := "[entity_mined] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 7 {
		return EntityEvent{}, fmt.Errorf("expected 7 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 8 {
		return EntityEvent{}, fmt.Errorf("expected 8 :-separated fields, got %d", len(parts))
	}

	var result EntityEvent
	var err error
	_ = err

	result.Event = "entity_mined"

	result.Name = parts[0]

	result.X, err = strconv.ParseFloat(parts[1], 64)
	if err != nil {
		return result, fmt.Errorf("invalid X %q: %w", parts[1], err)
	}

	result.Y, err = strconv.ParseFloat(parts[2], 64)
	if err != nil {
		return result, fmt.Errorf("invalid Y %q: %w", parts[2], err)
	}

	result.UnitNumber, err = strconv.ParseUint(parts[3], 10, 64)
	if err != nil {
		return result, fmt.Errorf("invalid UnitNumber %q: %w", parts[3], err)
	}

	result.SurfaceName = parts[4]

	result.SurfaceIndex, err = strconv.Atoi(parts[5])
	if err != nil {
		return result, fmt.Errorf("invalid SurfaceIndex %q: %w", parts[5], err)
	}

	result.PlayerIndex, err = strconv.Atoi(parts[6])
	if err != nil {
		return result, fmt.Errorf("invalid PlayerIndex %q: %w", parts[6], err)
	}

	if len(parts) > 7 {
		result.Cause = parts[7]
	}

	return result, nil
}

// Format returns the wire-format string for this EntityEvent.
func (m EntityEvent) Format() string {
	tag := m.Event
	return "[" + tag + "] " + m.Name + ":" + strconv.FormatFloat(m.X, 'f', 1, 64) + ":" + strconv.FormatFloat(m.Y, 'f', 1, 64) + ":" + strconv.FormatUint(m.UnitNumber, 10) + ":" + m.SurfaceName + ":" + strconv.Itoa(m.SurfaceIndex) + ":" + strconv.Itoa(m.PlayerIndex) + ":" + m.Cause
}
