// Code generated by go run ./gen -- DO NOT EDIT.

package playerattr

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParsePlayerEventPlayerJoined_RoundTrip(t *testing.T) {
	input := PlayerEvent{
		Event: "player_joined",
		Name:  "testName",
		Index: 42,
	}
	formatted := input.Format()
	parsed, err := ParsePlayerEventPlayerJoined(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.Equal(t, input.Index, parsed.Index)
}

func TestParsePlayerEventPlayerJoined_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid Index", input: "valid:notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParsePlayerEventPlayerJoined(tc.input)
			assert.Error(t, err)
		})
	}
}

func TestParsePlayerEventPlayerLeft_RoundTrip(t *testing.T) {
	input := PlayerEvent{
		Event: "player_left",
		Name:  "testName",
		Index: 42,
	}
	formatted := input.Format()
	parsed, err := ParsePlayerEventPlayerLeft(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.Equal(t, input.Index, parsed.Index)
}

func TestParsePlayerEventPlayerLeft_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid Index", input: "valid:notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParsePlayerEventPlayerLeft(tc.input)
			assert.Error(t, err)
		})
	}
}

func TestParsePlayerEventPlayerDied_RoundTrip(t *testing.T) {
	input := PlayerEvent{
		Event: "player_died",
		Name:  "testName",
		Index: 42,
	}
	formatted := input.Format()
	parsed, err := ParsePlayerEventPlayerDied(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.Equal(t, input.Index, parsed.Index)
}

func TestParsePlayerEventPlayerDied_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid Index", input: "valid:notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParsePlayerEventPlayerDied(tc.input)
			assert.Error(t, err)
		})
	}
}

func TestParsePlayerEventPlayerRespawned_RoundTrip(t *testing.T) {
	input := PlayerEvent{
		Event: "player_respawned",
		Name:  "testName",
		Index: 42,
	}
	formatted := input.Format()
	parsed, err := ParsePlayerEventPlayerRespawned(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.Equal(t, input.Index, parsed.Index)
}

func TestParsePlayerEventPlayerRespawned_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid Index", input: "valid:notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParsePlayerEventPlayerRespawned(tc.input)
			assert.Error(t, err)
		})
	}
}
