// Code generated by go run ./gen -- DO NOT EDIT.

package playerattr

import (
	"fmt"
	"strconv"
	"strings"
)

// ParsePlayerEventPlayerJoined parses a [player_joined] event message into a PlayerEvent.
func ParsePlayerEventPlayerJoined(msg string) (PlayerEvent, error) {
	payload := msg
	prefix := "[player_joined] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 2 {
		return PlayerEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 2 {
		return PlayerEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}

	var result PlayerEvent
	var err error
	_ = err

	result.Event = "player_joined"

	result.Name = parts[0]

	result.Index, err = strconv.Atoi(parts[1])
	if err != nil {
		return result, fmt.Errorf("invalid Index %q: %w", parts[1], err)
	}

	return result, nil
}

// ParsePlayerEventPlayerLeft parses a [player_left] event message into a PlayerEvent.
func ParsePlayerEventPlayerLeft(msg string) (PlayerEvent, error) {
	payload := msg
	prefix := "[player_left] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 2 {
		return PlayerEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 2 {
		return PlayerEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}

	var result PlayerEvent
	var err error
	_ = err

	result.Event = "player_left"

	result.Name = parts[0]

	result.Index, err = strconv.Atoi(parts[1])
	if err != nil {
		return result, fmt.Errorf("invalid Index %q: %w", parts[1], err)
	}

	return result, nil
}

// ParsePlayerEventPlayerDied parses a [player_died] event message into a PlayerEvent.
func ParsePlayerEventPlayerDied(msg string) (PlayerEvent, error) {
	payload := msg
	prefix := "[player_died] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 2 {
		return PlayerEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 2 {
		return PlayerEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}

	var result PlayerEvent
	var err error
	_ = err

	result.Event = "player_died"

	result.Name = parts[0]

	result.Index, err = strconv.Atoi(parts[1])
	if err != nil {
		return result, fmt.Errorf("invalid Index %q: %w", parts[1], err)
	}

	return result, nil
}

// ParsePlayerEventPlayerRespawned parses a [player_respawned] event message into a PlayerEvent.
func ParsePlayerEventPlayerRespawned(msg string) (PlayerEvent, error) {
	payload := msg
	prefix := "[player_respawned] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 2 {
		return PlayerEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 2 {
		return PlayerEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}

	var result PlayerEvent
	var err error
	_ = err

	result.Event = "player_respawned"

	result.Name = parts[0]

	result.Index, err = strconv.Atoi(parts[1])
	if err != nil {
		return result, fmt.Errorf("invalid Index %q: %w", parts[1], err)
	}

	return result, nil
}

// Format returns the wire-format string for this PlayerEvent.
func (m PlayerEvent) Format() string {
	tag := m.Event
	return "[" + tag + "] " + m.Name + ":" + strconv.Itoa(m.Index)
}
