// Code generated by go run ./gen -- DO NOT EDIT.

package surface

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseSurfaceEventSurfaceCreated_RoundTrip(t *testing.T) {
	input := SurfaceEvent{
		Event: "surface_created",
		Name:  "testName",
		Index: 42,
	}
	formatted := input.Format()
	parsed, err := ParseSurfaceEventSurfaceCreated(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.Equal(t, input.Index, parsed.Index)
}

func TestParseSurfaceEventSurfaceCreated_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid Index", input: "valid:notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseSurfaceEventSurfaceCreated(tc.input)
			assert.Error(t, err)
		})
	}
}

func TestParseSurfaceEventSurfaceDeleted_RoundTrip(t *testing.T) {
	input := SurfaceEvent{
		Event: "surface_deleted",
		Name:  "testName",
		Index: 42,
	}
	formatted := input.Format()
	parsed, err := ParseSurfaceEventSurfaceDeleted(formatted)
	require.NoError(t, err)
	assert.Equal(t, input.Name, parsed.Name)
	assert.Equal(t, input.Index, parsed.Index)
}

func TestParseSurfaceEventSurfaceDeleted_Errors(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{name: "empty string", input: ""},
		{name: "too few fields", input: "x"},
		{name: "invalid Index", input: "valid:notanumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseSurfaceEventSurfaceDeleted(tc.input)
			assert.Error(t, err)
		})
	}
}
