// Code generated by go run ./gen -- DO NOT EDIT.

package surface

import (
	"fmt"
	"strconv"
	"strings"
)

// ParseSurfaceEventSurfaceCreated parses a [surface_created] event message into a SurfaceEvent.
func ParseSurfaceEventSurfaceCreated(msg string) (SurfaceEvent, error) {
	payload := msg
	prefix := "[surface_created] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 2 {
		return SurfaceEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 2 {
		return SurfaceEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}

	var result SurfaceEvent
	var err error
	_ = err

	result.Event = "surface_created"

	result.Name = parts[0]

	result.Index, err = strconv.Atoi(parts[1])
	if err != nil {
		return result, fmt.Errorf("invalid Index %q: %w", parts[1], err)
	}

	return result, nil
}

// ParseSurfaceEventSurfaceDeleted parses a [surface_deleted] event message into a SurfaceEvent.
func ParseSurfaceEventSurfaceDeleted(msg string) (SurfaceEvent, error) {
	payload := msg
	prefix := "[surface_deleted] "
	if strings.HasPrefix(msg, prefix) {
		payload = msg[len(prefix):]
	}

	parts := strings.Split(payload, ":")
	if len(parts) < 2 {
		return SurfaceEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}
	if len(parts) > 2 {
		return SurfaceEvent{}, fmt.Errorf("expected 2 :-separated fields, got %d", len(parts))
	}

	var result SurfaceEvent
	var err error
	_ = err

	result.Event = "surface_deleted"

	result.Name = parts[0]

	result.Index, err = strconv.Atoi(parts[1])
	if err != nil {
		return result, fmt.Errorf("invalid Index %q: %w", parts[1], err)
	}

	return result, nil
}

// Format returns the wire-format string for this SurfaceEvent.
func (m SurfaceEvent) Format() string {
	tag := m.Event
	return "[" + tag + "] " + m.Name + ":" + strconv.Itoa(m.Index)
}
