// Code generated by nRPC protoc plugin. DO NOT EDIT.
package api

import (
	"context"
	"log"
	"time"

	"google.golang.org/protobuf/proto"
	"github.com/nats-io/nats.go"
	"github.com/nats-rpc/nrpc"
)

// CommandServer is the interface that providers of the service
// Command should implement.
type CommandServer interface {
	Execute(ctx context.Context, req *CommandPayload) (*CommandResult, error)
}

// CommandHandler provides a NATS subscription handler that can serve a
// subscription using a given CommandServer implementation.
type CommandHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  CommandServer

	encodings []string
}

func NewCommandHandler(ctx context.Context, nc nrpc.NatsConn, s CommandServer) *CommandHandler {
	return &CommandHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewCommandConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s CommandServer) *CommandHandler {
	return &CommandHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *CommandHandler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *CommandHandler) Subject() string {
	return "Command.>"
}

func (h *CommandHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"", 0, "Command", 0, msg.Subject)
	if err != nil {
		log.Printf("CommandHanlder: Command subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "Execute":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("ExecuteHanlder: Execute subject parsing failed: %v", err)
			break
		}
		var req CommandPayload
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("ExecuteHandler: Execute request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.Execute(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	default:
		log.Printf("CommandHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("CommandHandler: Command handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type CommandClient struct {
	nc      nrpc.NatsConn
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewCommandClient(nc nrpc.NatsConn) *CommandClient {
	return &CommandClient{
		nc:      nc,
		Subject: "Command",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *CommandClient) Execute(req *CommandPayload) (*CommandResult, error) {

	subject := c.Subject + "." + "Execute"

	// call
	var resp = CommandResult{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

// RconServer is the interface that providers of the service
// Rcon should implement.
type RconServer interface {
	Execute(ctx context.Context, req *RconCommand) (*RconResult, error)
}

// RconHandler provides a NATS subscription handler that can serve a
// subscription using a given RconServer implementation.
type RconHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  RconServer

	encodings []string
}

func NewRconHandler(ctx context.Context, nc nrpc.NatsConn, s RconServer) *RconHandler {
	return &RconHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewRconConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s RconServer) *RconHandler {
	return &RconHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *RconHandler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *RconHandler) Subject() string {
	return "Rcon.>"
}

func (h *RconHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"", 0, "Rcon", 0, msg.Subject)
	if err != nil {
		log.Printf("RconHanlder: Rcon subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "Execute":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("ExecuteHanlder: Execute subject parsing failed: %v", err)
			break
		}
		var req RconCommand
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("ExecuteHandler: Execute request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.Execute(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	default:
		log.Printf("RconHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("RconHandler: Rcon handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type RconClient struct {
	nc      nrpc.NatsConn
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewRconClient(nc nrpc.NatsConn) *RconClient {
	return &RconClient{
		nc:      nc,
		Subject: "Rcon",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *RconClient) Execute(req *RconCommand) (*RconResult, error) {

	subject := c.Subject + "." + "Execute"

	// call
	var resp = RconResult{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

// SoftModServer is the interface that providers of the service
// SoftMod should implement.
type SoftModServer interface {
	ApplySoftMod(ctx context.Context, req *SoftModRequest) (*Empty, error)
}

// SoftModHandler provides a NATS subscription handler that can serve a
// subscription using a given SoftModServer implementation.
type SoftModHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  SoftModServer

	encodings []string
}

func NewSoftModHandler(ctx context.Context, nc nrpc.NatsConn, s SoftModServer) *SoftModHandler {
	return &SoftModHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewSoftModConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s SoftModServer) *SoftModHandler {
	return &SoftModHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *SoftModHandler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *SoftModHandler) Subject() string {
	return "SoftMod.>"
}

func (h *SoftModHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"", 0, "SoftMod", 0, msg.Subject)
	if err != nil {
		log.Printf("SoftModHanlder: SoftMod subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "ApplySoftMod":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("ApplySoftModHanlder: ApplySoftMod subject parsing failed: %v", err)
			break
		}
		var req SoftModRequest
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("ApplySoftModHandler: ApplySoftMod request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.ApplySoftMod(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	default:
		log.Printf("SoftModHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("SoftModHandler: SoftMod handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type SoftModClient struct {
	nc      nrpc.NatsConn
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewSoftModClient(nc nrpc.NatsConn) *SoftModClient {
	return &SoftModClient{
		nc:      nc,
		Subject: "SoftMod",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *SoftModClient) ApplySoftMod(req *SoftModRequest) (*Empty, error) {

	subject := c.Subject + "." + "ApplySoftMod"

	// call
	var resp = Empty{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

// SettingsServer is the interface that providers of the service
// Settings should implement.
type SettingsServer interface {
	ServerAdmins(ctx context.Context, req *ServerAdminsType) (*ServerAdminsType, error)
}

// SettingsHandler provides a NATS subscription handler that can serve a
// subscription using a given SettingsServer implementation.
type SettingsHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  SettingsServer

	encodings []string
}

func NewSettingsHandler(ctx context.Context, nc nrpc.NatsConn, s SettingsServer) *SettingsHandler {
	return &SettingsHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewSettingsConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s SettingsServer) *SettingsHandler {
	return &SettingsHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *SettingsHandler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *SettingsHandler) Subject() string {
	return "Settings.>"
}

func (h *SettingsHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"", 0, "Settings", 0, msg.Subject)
	if err != nil {
		log.Printf("SettingsHanlder: Settings subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "ServerAdmins":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("ServerAdminsHanlder: ServerAdmins subject parsing failed: %v", err)
			break
		}
		var req ServerAdminsType
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("ServerAdminsHandler: ServerAdmins request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.ServerAdmins(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	default:
		log.Printf("SettingsHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("SettingsHandler: Settings handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type SettingsClient struct {
	nc      nrpc.NatsConn
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewSettingsClient(nc nrpc.NatsConn) *SettingsClient {
	return &SettingsClient{
		nc:      nc,
		Subject: "Settings",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *SettingsClient) ServerAdmins(req *ServerAdminsType) (*ServerAdminsType, error) {

	subject := c.Subject + "." + "ServerAdmins"

	// call
	var resp = ServerAdminsType{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	Command *CommandClient
	Rcon *RconClient
	SoftMod *SoftModClient
	Settings *SettingsClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
	}
	c.Command = NewCommandClient(nc)
	c.Rcon = NewRconClient(nc)
	c.SoftMod = NewSoftModClient(nc)
	c.Settings = NewSettingsClient(nc)
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.Command != nil {
		c.Command.Encoding = encoding
	}
	if c.Rcon != nil {
		c.Rcon.Encoding = encoding
	}
	if c.SoftMod != nil {
		c.SoftMod.Encoding = encoding
	}
	if c.Settings != nil {
		c.Settings.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.Command != nil {
		c.Command.Timeout = t
	}
	if c.Rcon != nil {
		c.Rcon.Timeout = t
	}
	if c.SoftMod != nil {
		c.SoftMod.Timeout = t
	}
	if c.Settings != nil {
		c.Settings.Timeout = t
	}
}